### ISSUE TITLE
'platform' is not exported by node-resolve:empty.js

### ISSUE THREAD

**Issue by jesperp** [contentful/contentful-sdk-core#120]
Hi,
When setting up a simple browser based project with snowpack (probably rollup as well). Importing contentful (`import {createClient} from 'contentful'`) generates the following error:

```
[snowpack] ! installing dependencies...
[snowpack] Failed to load node_modules/.pnpm/contentful-sdk-core@6.7.0/node_modules/contentful-sdk-core/dist/index.es-modules.js
  'platform' is not exported by node-resolve:empty.js, imported by node_modules/.pnpm/contentful-sdk-core@6.7.0/node_modules/contentful-sdk-core/dist/index.es-modules.js
[snowpack] Install failed.
```
Main tools used: Svelte, typescript, Snowpack

I have solved this simply by editing the file in question as suggested here:
https://github.com/snowpackjs/snowpack/discussions/1387#discussioncomment-117946
```
# file: node_modules/.pnpm/contentful-sdk-core@6.7.0/node_modules/contentful-sdk-core/dist/index.es-modules.js
- import { platform, release } from 'os';
+ import os from 'os';
```

But it would of course be nice if this was fixed by contentful!

Steps to reproduce
```
npx create-snowpack-app myproject --template @snowpack/app-template-svelte-typescript
cd myproject
npm i contentful
# edit src/App.svelte and add import 'contentful' inside <script> tag
npm start
```

**Comment by KrisStadler** [comment]
Still getting this error when using Contentful JS version 8.3.6

**Comment by KrisStadler** [comment]
@luizfonseca Thank you for the assistance! What's the timeline for getting this PR merged?

**Comment by luizfonseca** [comment]
@KrisStadler We need to test if the branch has any regressions not captured by the tests since this is used by other SDKs

**Comment by angelmeraz** [comment]
Same issue happens with **SvelteKit** which uses **Vite**:

```
sveltekit % npm run dev --

> ~TODO~@0.0.1 dev /Users/***/dev/sveltekit
> svelte-kit dev


  SvelteKit v1.0.0-next.109

  local:   http://localhost:5000
  network: not exposed

  Use --host to expose server to other devices on this network


10:12:55 [vite] new dependencies found: contentful, updating...
 > node_modules/contentful-sdk-core/dist/index.es-modules.js:3:9: error: No matching export in "browser-external:os" for import "platform"
    3 │ import { platform, release } from 'os';
      ╵          ~~~~~~~~

 > node_modules/contentful-sdk-core/dist/index.es-modules.js:3:19: error: No matching export in "browser-external:os" for import "release"
    3 │ import { platform, release } from 'os';
      ╵                    ~~~~~~~

10:12:55 [vite] error while updating dependencies:
Error: Build failed with 2 errors:
node_modules/contentful-sdk-core/dist/index.es-modules.js:3:9: error: No matching export in "browser-external:os" for import "platform"
node_modules/contentful-sdk-core/dist/index.es-modules.js:3:19: error: No matching export in "browser-external:os" for import "release"
    at failureErrorWithLog (/Users/angel.meraz/dev/sveltekit/node_modules/esbuild/lib/main.js:1443:15)
    at /Users/angel.meraz/dev/sveltekit/node_modules/esbuild/lib/main.js:1125:28
    at runOnEndCallbacks (/Users/angel.meraz/dev/sveltekit/node_modules/esbuild/lib/main.js:915:63)
    at buildResponseToResult (/Users/angel.meraz/dev/sveltekit/node_modules/esbuild/lib/main.js:1123:7)
    at /Users/angel.meraz/dev/sveltekit/node_modules/esbuild/lib/main.js:1230:14
    at /Users/angel.meraz/dev/sveltekit/node_modules/esbuild/lib/main.js:606:9
    at handleIncomingPacket (/Users/angel.meraz/dev/sveltekit/node_modules/esbuild/lib/main.js:703:9)
    at Socket.readFromStdout (/Users/angel.meraz/dev/sveltekit/node_modules/esbuild/lib/main.js:573:7)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
```

However it does work by updating `contentful-sdk-core/dist/index.es-modules.js` as suggested by @jesperp

**Comment by luizfonseca** [comment]
@KrisStadler @angelmeraz could you let me know if my branch fixes the issue? https://github.com/contentful/contentful-sdk-core/pull/161

you can replace it in your package.json:

```
"contentful-sdk-core": "contentful/contentful-sdk-core#fix/os-error"
```

**Comment by KrisStadler** [comment]
@luizfonseca I'll take a look at it. I Will post feedback soon

**Comment by angelmeraz** [comment]
@luizfonseca I gave this a try and got the following error:
```sveltekit-contentful-app % npm run dev --

> sveltekit-contentful-app@0.0.1 dev /Users/angel.meraz/dev/sveltekit-contentful-app
> svelte-kit dev


  SvelteKit v1.0.0-next.109

  local:   http://localhost:3000
  network: not exposed

  Use --host to expose server to other devices on this network


10:35:23 [vite] hmr update /src/routes/index.svelte
10:35:28 [vite] new dependencies found: contentful, updating...
 > node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:14: error: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "contentful-sdk-core". The package may have incorrect main/module/exports specified in its package.json.
    32580 │         throw new Error(`Failed to resolve entry for package "${id}". ` +
          ╵               ^
    at resolvePackageEntry (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:15)
    at tryNodeResolve (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32399:11)
    at Context.resolveId (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32282:28)
    at Object.resolveId (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:44228:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:69926:27
    at async /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64628:34
    at async callback (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:809:28)
    at async handleRequest (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:641:30)

   node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64615:18: note: This error came from the "onResolve" callback registered here
    64615 │             build.onResolve({ filter: /^[\w@][^:]/ }, async ({ path: id, importer, kind, resolveDir }) => {
          ╵                   ~~~~~~~~~
    at setup (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64615:19)
    at handlePlugins (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:733:23)
    at Object.buildOrServe (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1018:7)
    at /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1742:17
    at new Promise (<anonymous>)
    at Object.build (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1741:14)
    at Object.build (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1617:51)
    at optimizeDeps (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64842:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

   node_modules/contentful/dist/es-modules/contentful.js:10:33: note: The plugin "vite:dep-pre-bundle" was triggered by this import
       10 │ var _contentfulSdkCore = require("contentful-sdk-core");
          ╵                                  ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:14: error: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "contentful-sdk-core". The package may have incorrect main/module/exports specified in its package.json.
    32580 │         throw new Error(`Failed to resolve entry for package "${id}". ` +
          ╵               ^
    at resolvePackageEntry (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:15)
    at tryNodeResolve (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32399:11)
    at Context.resolveId (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32282:28)
    at Object.resolveId (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:44228:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:69926:27
    at async /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64628:34
    at async callback (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:809:28)
    at async handleRequest (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:641:30)

   node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64615:18: note: This error came from the "onResolve" callback registered here
    64615 │             build.onResolve({ filter: /^[\w@][^:]/ }, async ({ path: id, importer, kind, resolveDir }) => {
          ╵                   ~~~~~~~~~
    at setup (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64615:19)
    at handlePlugins (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:733:23)
    at Object.buildOrServe (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1018:7)
    at /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1742:17
    at new Promise (<anonymous>)
    at Object.build (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1741:14)
    at Object.build (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1617:51)
    at optimizeDeps (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64842:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

   node_modules/contentful/dist/es-modules/create-contentful-api.js:8:33: note: The plugin "vite:dep-pre-bundle" was triggered by this import
        8 │ var _contentfulSdkCore = require("contentful-sdk-core");
          ╵                                  ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:14: error: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "contentful-sdk-core". The package may have incorrect main/module/exports specified in its package.json.
    32580 │         throw new Error(`Failed to resolve entry for package "${id}". ` +
          ╵               ^
    at resolvePackageEntry (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:15)
    at tryNodeResolve (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32399:11)
    at Context.resolveId (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32282:28)
    at Object.resolveId (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:44228:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:69926:27
    at async /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64628:34
    at async callback (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:809:28)
    at async handleRequest (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:641:30)

   node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64615:18: note: This error came from the "onResolve" callback registered here
    64615 │             build.onResolve({ filter: /^[\w@][^:]/ }, async ({ path: id, importer, kind, resolveDir }) => {
          ╵                   ~~~~~~~~~
    at setup (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64615:19)
    at handlePlugins (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:733:23)
    at Object.buildOrServe (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1018:7)
    at /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1742:17
    at new Promise (<anonymous>)
    at Object.build (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1741:14)
    at Object.build (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1617:51)
    at optimizeDeps (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64842:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

   node_modules/contentful/dist/es-modules/entities/space.js:8:33: note: The plugin "vite:dep-pre-bundle" was triggered by this import
        8 │ var _contentfulSdkCore = require("contentful-sdk-core");
          ╵                                  ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:14: error: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "contentful-sdk-core". The package may have incorrect main/module/exports specified in its package.json.
    32580 │         throw new Error(`Failed to resolve entry for package "${id}". ` +
          ╵               ^
    at resolvePackageEntry (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:15)
    at tryNodeResolve (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32399:11)
    at Context.resolveId (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32282:28)
    at Object.resolveId (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:44228:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:69926:27
    at async /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64628:34
    at async callback (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:809:28)
    at async handleRequest (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:641:30)

   node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64615:18: note: This error came from the "onResolve" callback registered here
    64615 │             build.onResolve({ filter: /^[\w@][^:]/ }, async ({ path: id, importer, kind, resolveDir }) => {
          ╵                   ~~~~~~~~~
    at setup (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64615:19)
    at handlePlugins (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:733:23)
    at Object.buildOrServe (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1018:7)
    at /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1742:17
    at new Promise (<anonymous>)
    at Object.build (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1741:14)
    at Object.build (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1617:51)
    at optimizeDeps (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64842:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

   node_modules/contentful/dist/es-modules/paged-sync.js:8:33: note: The plugin "vite:dep-pre-bundle" was triggered by this import
        8 │ var _contentfulSdkCore = require("contentful-sdk-core");
          ╵                                  ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:14: error: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "contentful-sdk-core". The package may have incorrect main/module/exports specified in its package.json.
    32580 │         throw new Error(`Failed to resolve entry for package "${id}". ` +
          ╵               ^
    at resolvePackageEntry (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:15)
    at tryNodeResolve (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32399:11)
    at Context.resolveId (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32282:28)
    at Object.resolveId (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:44228:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:69926:27
    at async /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64628:34
    at async callback (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:809:28)
    at async handleRequest (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:641:30)

   node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64615:18: note: This error came from the "onResolve" callback registered here
    64615 │             build.onResolve({ filter: /^[\w@][^:]/ }, async ({ path: id, importer, kind, resolveDir }) => {
          ╵                   ~~~~~~~~~
    at setup (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64615:19)
    at handlePlugins (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:733:23)
    at Object.buildOrServe (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1018:7)
    at /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1742:17
    at new Promise (<anonymous>)
    at Object.build (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1741:14)
    at Object.build (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1617:51)
    at optimizeDeps (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64842:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

   node_modules/contentful/dist/es-modules/entities/asset-key.js:10:33: note: The plugin "vite:dep-pre-bundle" was triggered by this import
       10 │ var _contentfulSdkCore = require("contentful-sdk-core");
          ╵                                  ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:14: error: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "contentful-sdk-core". The package may have incorrect main/module/exports specified in its package.json.
    32580 │         throw new Error(`Failed to resolve entry for package "${id}". ` +
          ╵               ^
    at resolvePackageEntry (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:15)
    at tryNodeResolve (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32399:11)
    at Context.resolveId (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32282:28)
    at Object.resolveId (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:44228:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:69926:27
    at async /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64628:34
    at async callback (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:809:28)
    at async handleRequest (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:641:30)

   node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64615:18: note: This error came from the "onResolve" callback registered here
    64615 │             build.onResolve({ filter: /^[\w@][^:]/ }, async ({ path: id, importer, kind, resolveDir }) => {
          ╵                   ~~~~~~~~~
    at setup (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64615:19)
    at handlePlugins (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:733:23)
    at Object.buildOrServe (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1018:7)
    at /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1742:17
    at new Promise (<anonymous>)
    at Object.build (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1741:14)
    at Object.build (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1617:51)
    at optimizeDeps (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64842:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

   node_modules/contentful/dist/es-modules/entities/asset.js:11:33: note: The plugin "vite:dep-pre-bundle" was triggered by this import
       11 │ var _contentfulSdkCore = require("contentful-sdk-core");
          ╵                                  ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:14: error: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "contentful-sdk-core". The package may have incorrect main/module/exports specified in its package.json.
    32580 │         throw new Error(`Failed to resolve entry for package "${id}". ` +
          ╵               ^
    at resolvePackageEntry (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:15)
    at tryNodeResolve (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32399:11)
    at Context.resolveId (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32282:28)
    at Object.resolveId (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:44228:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:69926:27
    at async /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64628:34
    at async callback (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:809:28)
    at async handleRequest (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:641:30)

   node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64615:18: note: This error came from the "onResolve" callback registered here
    64615 │             build.onResolve({ filter: /^[\w@][^:]/ }, async ({ path: id, importer, kind, resolveDir }) => {
          ╵                   ~~~~~~~~~
    at setup (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64615:19)
    at handlePlugins (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:733:23)
    at Object.buildOrServe (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1018:7)
    at /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1742:17
    at new Promise (<anonymous>)
    at Object.build (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1741:14)
    at Object.build (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1617:51)
    at optimizeDeps (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64842:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

   node_modules/contentful/dist/es-modules/entities/locale.js:11:33: note: The plugin "vite:dep-pre-bundle" was triggered by this import
       11 │ var _contentfulSdkCore = require("contentful-sdk-core");
          ╵                                  ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:14: error: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "contentful-sdk-core". The package may have incorrect main/module/exports specified in its package.json.
    32580 │         throw new Error(`Failed to resolve entry for package "${id}". ` +
          ╵               ^
    at resolvePackageEntry (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:15)
    at tryNodeResolve (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32399:11)
    at Context.resolveId (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32282:28)
    at Object.resolveId (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:44228:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:69926:27
    at async /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64628:34
    at async callback (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:809:28)
    at async handleRequest (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:641:30)

   node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64615:18: note: This error came from the "onResolve" callback registered here
    64615 │             build.onResolve({ filter: /^[\w@][^:]/ }, async ({ path: id, importer, kind, resolveDir }) => {
          ╵                   ~~~~~~~~~
    at setup (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64615:19)
    at handlePlugins (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:733:23)
    at Object.buildOrServe (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1018:7)
    at /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1742:17
    at new Promise (<anonymous>)
    at Object.build (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1741:14)
    at Object.build (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1617:51)
    at optimizeDeps (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64842:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

   node_modules/contentful/dist/es-modules/entities/content-type.js:11:33: note: The plugin "vite:dep-pre-bundle" was triggered by this import
       11 │ var _contentfulSdkCore = require("contentful-sdk-core");
          ╵                                  ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:14: error: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "contentful-sdk-core". The package may have incorrect main/module/exports specified in its package.json.
    32580 │         throw new Error(`Failed to resolve entry for package "${id}". ` +
          ╵               ^
    at resolvePackageEntry (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:15)
    at tryNodeResolve (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32399:11)
    at Context.resolveId (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32282:28)
    at Object.resolveId (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:44228:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:69926:27
    at async /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64628:34
    at async callback (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:809:28)
    at async handleRequest (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:641:30)

   node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64615:18: note: This error came from the "onResolve" callback registered here
    64615 │             build.onResolve({ filter: /^[\w@][^:]/ }, async ({ path: id, importer, kind, resolveDir }) => {
          ╵                   ~~~~~~~~~
    at setup (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64615:19)
    at handlePlugins (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:733:23)
    at Object.buildOrServe (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1018:7)
    at /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1742:17
    at new Promise (<anonymous>)
    at Object.build (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1741:14)
    at Object.build (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1617:51)
    at optimizeDeps (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:64842:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

   node_modules/contentful/dist/es-modules/entities/entry.js:11:33: note: The plugin "vite:dep-pre-bundle" was triggered by this import
       11 │ var _contentfulSdkCore = require("contentful-sdk-core");
          ╵                                  ~~~~~~~~~~~~~~~~~~~~~

10:35:29 [vite] error while updating dependencies:
Error: Build failed with 9 errors:
node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:14: error: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "contentful-sdk-core". The package may have incorrect main/module/exports specified in its package.json.
node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:14: error: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "contentful-sdk-core". The package may have incorrect main/module/exports specified in its package.json.
node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:14: error: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "contentful-sdk-core". The package may have incorrect main/module/exports specified in its package.json.
node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:14: error: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "contentful-sdk-core". The package may have incorrect main/module/exports specified in its package.json.
node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:32580:14: error: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "contentful-sdk-core". The package may have incorrect main/module/exports specified in its package.json.
...
    at failureErrorWithLog (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1443:15)
    at /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1125:28
    at runOnEndCallbacks (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:915:63)
    at buildResponseToResult (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1123:7)
    at /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1230:14
    at /Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:606:9
    at handleIncomingPacket (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:703:9)
    at Socket.readFromStdout (/Users/angel.meraz/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:573:7)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
```

package.json
```
{
  "name": "sveltekit-contentful-app",
  "version": "0.0.1",
  "scripts": {
    "dev": "svelte-kit dev",
    "build": "svelte-kit build",
    "preview": "svelte-kit preview",
    "lint": "prettier --check --plugin-search-dir=. . && eslint --ignore-path .gitignore .",
    "format": "prettier --write --plugin-search-dir=. ."
  },
  "devDependencies": {
    "@sveltejs/kit": "next",
    "@typescript-eslint/eslint-plugin": "^4.19.0",
    "@typescript-eslint/parser": "^4.19.0",
    "contentful-sdk-core": "git://github.com/contentful/contentful-sdk-core.git#fix/os-error",
    "eslint": "^7.22.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-svelte3": "^3.2.0",
    "prettier": "~2.2.1",
    "prettier-plugin-svelte": "^2.2.0",
    "svelte": "^3.34.0",
    "svelte-preprocess": "^4.0.0",
    "tslib": "^2.0.0",
    "typescript": "^4.0.0",
    "vite": "^2.3.4"
  },
  "type": "module",
  "dependencies": {
    "contentful": "^8.3.6",
    "dotenv": "^10.0.0",
    "path": "^0.12.7"
  }
}

```

**Comment by luizfonseca** [comment]
@angelmeraz seems like an installation problem 🤔 (it's not installing the sdk) -- I will check with a clean project as soon as I have the time.

Not sure if it's intended, could you try also making it a normal dependency (not just a `devDependency`)?

**Comment by angelmeraz** [comment]
My bad there. Here it goes again, still having the same issue as before.

```> sveltekit-contentful-app@0.0.1 dev /Users/****/dev/sveltekit-contentful-app
> svelte-kit dev


  SvelteKit v1.0.0-next.111

  local:   http://localhost:3000
  network: not exposed

  Use --host to expose server to other devices on this network


09:08:25 [vite] new dependencies found: contentful, updating...
 > node_modules/contentful/node_modules/contentful-sdk-core/dist/index.es-modules.js:3:9: error: No matching export in "browser-external:os" for import "platform"
    3 │ import { platform, release } from 'os';
      ╵          ~~~~~~~~

 > node_modules/contentful/node_modules/contentful-sdk-core/dist/index.es-modules.js:3:19: error: No matching export in "browser-external:os" for import "release"
    3 │ import { platform, release } from 'os';
      ╵                    ~~~~~~~

09:08:26 [vite] error while updating dependencies:
Error: Build failed with 2 errors:
node_modules/contentful/node_modules/contentful-sdk-core/dist/index.es-modules.js:3:9: error: No matching export in "browser-external:os" for import "platform"
node_modules/contentful/node_modules/contentful-sdk-core/dist/index.es-modules.js:3:19: error: No matching export in "browser-external:os" for import "release"
    at failureErrorWithLog (/Users/****/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1443:15)
    at /Users/****/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1125:28
    at runOnEndCallbacks (/Users/****/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:915:63)
    at buildResponseToResult (/Users/****/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1123:7)
    at /Users/****/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:1230:14
    at /Users/****/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:606:9
    at handleIncomingPacket (/Users/****/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:703:9)
    at Socket.readFromStdout (/Users/****/dev/sveltekit-contentful-app/node_modules/esbuild/lib/main.js:573:7)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
```

package.json

```
{
  "name": "sveltekit-contentful-app",
  "version": "0.0.1",
  "scripts": {
    "dev": "svelte-kit dev",
    "build": "svelte-kit build",
    "preview": "svelte-kit preview",
    "lint": "prettier --check --plugin-search-dir=. . && eslint --ignore-path .gitignore .",
    "format": "prettier --write --plugin-search-dir=. ."
  },
  "devDependencies": {
    "@sveltejs/kit": "next",
    "@typescript-eslint/eslint-plugin": "^4.19.0",
    "@typescript-eslint/parser": "^4.19.0",
    "eslint": "^7.22.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-svelte3": "^3.2.0",
    "prettier": "~2.2.1",
    "prettier-plugin-svelte": "^2.2.0",
    "svelte": "^3.34.0",
    "svelte-preprocess": "^4.0.0",
    "tslib": "^2.0.0",
    "typescript": "^4.0.0",
    "vite": "^2.3.4"
  },
  "type": "module",
  "dependencies": {
    "contentful": "^8.3.6",
    "contentful-sdk-core": "git://github.com/contentful/contentful-sdk-core.git#fix/os-error",
    "dotenv": "^10.0.0",
    "path": "^0.12.7"
  }
}
```

**Comment by LionOnTheWeb** [comment]
@angelmeraz , that's because you're installing the fix for contentful-sdk-core in the root node_modules directory. But the sdk core is a nested dependency for contentful, so contentful is still using the broken nested dependency. You might have to write a special build function to include the installation of the sub-dependency.

**Comment by LionOnTheWeb** [comment]
I've been working on resolving this error as well as it's currently impacting my project which uses Svelte and Contentful. So far the steps I've taken to reduce errors and make progress is as follows: 

In `package.json` install the fix version of contentful-sdk-core as a dependency (instead of dev dependency)
``` javascript
"dependencies": {
    "contentful": "^8.3.7",
    "contentful-sdk-core": "git://github.com/contentful/contentful-sdk-core.git#fix/os-error",
    ...
}
```

Then, this error went away:
```
[!] Error: 'platform' is not exported by node-resolve:empty.js, imported by node_modules/contentful-sdk-core/dist/index.es-modules.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
```

But produced these warnings and broke my build anyway:
```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
contentful-sdk-core (imported by contentful-sdk-core?commonjs-external)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
contentful-sdk-core (guessing '_contentfulSdkCore')
```

So working through them, I fixed the missing global variable name warning by adding a `globals` field to the output  object in `rollup.config.js` like so:
```javascript
export default {
	input: 'src/main.js',
	output: {
                 ...
		globals: {
			'contentful-sdk-core': '_contentfulSdkCore'
		}
	}, ...
```

And finally for the unresolved dependencies, I followed the doc linked in the warning message and added an `external` option to the export default for `contentful-sdk-core`:
```javascript
export default {
    output: {
        ...
    },
    ...
    external: ['contentful-sdk-core']
```

After making those changes, the warnings are suppressed  and the app finally compiles, however, it breaks immediately and I get a console error in the browser stating: `Uncaught ReferenceError: _contentfulSdkCore is not defined`

**Comment by LionOnTheWeb** [comment]
@luizfonseca Any update on this? Can't get past a broken production build because of this

**Comment by Chipsnet** [comment]
If I can't solve this problem, I will have to stop adopting contentful because I can't use contentful with svelte.

**Comment by fforres** [comment]
Wouldn't an inline require for the `getNodeOS` function allow for this to be bundled for web?

```
function getNodeOS() {
  var os = require('os').platform() || 'linux';
  var version = require('os').release() || '0.0.0';
  {....more code ....}
}
```

**Comment by wwedmedyk** [comment]
This error is also occuring in stencil.js projects using contentful

**Comment by pfumagalli** [comment]
For those stumbling here after seeing the error on Vite, you can still use the CJS version which works a-ok-ish :-) Your `vite.config.ts` (or `.js`) should include:

```typescript
export default defineConfig({
  // ... all your configs are belong to us
  resolve: {
    // solve a little problem with ESM version of contentful-sdk-core
    alias: [ {
      find: 'contentful-sdk-core',
      replacement: 'contentful-sdk-core/dist/index.js'
    } ],
  },
})
```

**Comment by ruderngespra** [comment]
Hey everyone,

I am sorry this took so long! We just published a [canary release](https://github.com/contentful/contentful.js/releases/tag/v8.5.1) that hopefully should fix the issue.

Could you try and install `contentful@next` in your projects and confirm if this works for you?

**Comment by wwedmedyk** [comment]
> Hey everyone,
> 
> I am sorry this took so long! We just published a [canary release](https://github.com/contentful/contentful.js/releases/tag/v8.5.1) that hopefully should fix the issue.
> 
> Could you try and install `contentful@next` in your projects and confirm if this works for you?

@ruderngespra This does not resolve the issue inside of a stencil application: 

<img width="718" alt="Screen Shot 2021-08-31 at 11 09 01 AM" src="https://user-images.githubusercontent.com/74321133/131528148-b56bd819-d6ed-4881-941b-3960d8837e4b.png">
<img width="449" alt="Screen Shot 2021-08-31 at 11 09 26 AM" src="https://user-images.githubusercontent.com/74321133/131528208-d299a714-7bd7-4800-b8ee-872228659660.png">

**Comment by pfumagalli** [comment]
I can confirm that with the new release the hack above for Vue/Vite is no longer necessary!

**Comment by ruderngespra** [comment]
Glad to hear! The fix has been merged to the main branch in v.8.5.3 of [contentful.js](https://github.com/contentful/contentful.js/)

**Comment by angelmeraz** [comment]
I'm trying this out on a brand new SvelteKit project and I'm getting `undefined` from:

`import contentful from 'contentful';`

**Comment by angelmeraz** [comment]
`import * as contentful from 'contentful';`
and
`import { createClient } from 'contentful';`

... seem to work!

**Comment by marblegravy** [comment]
> Hey everyone,
> 
> I am sorry this took so long! We just published a [canary release](https://github.com/contentful/contentful.js/releases/tag/v8.5.1) that hopefully should fix the issue.
> 
> Could you try and install `contentful@next` in your projects and confirm if this works for you?

I'm doing this today and am still getting an error.

`❯ npx vite --port=4000       
Pre-bundling dependencies:
  vue
  contentful-vue
(this will be run only when your dependencies or config have changed)
✘ [ERROR] No matching export in "browser-external:os" for import "platform"

    node_modules/contentful-vue/node_modules/contentful-sdk-core/dist/es-modules/get-user-agent.js:1:9:
      1 │ import { platform, release } from 'os';
        ╵          ~~~~~~~~

✘ [ERROR] No matching export in "browser-external:os" for import "release"

    node_modules/contentful-vue/node_modules/contentful-sdk-core/dist/es-modules/get-user-agent.js:1:19:
      1 │ import { platform, release } from 'os';`

manually changing the line in get-user-agent.js to `import os from 'os';` resolves it and I can build and run a local environment.

**Comment by pfumagalli** [comment]
@marblegravy 

> ```
> node_modules/contentful-vue/node_modules/contentful-sdk-core/dist/es-modules/get-user-agent.js:1:9:
>   1 │ import { platform, release } from 'os';
>     ╵          ~~~~~~~~
> ```

The error is from a sub-dependency of `contentful-vue` (see path: `node_modules/contentful-vue/node_modules/contentful-sdk-core`) which uses an obsolete dependency of `contentful`.
